export const INITIAL_WITNESS_FORM = {
  faceShape: '',
  skinTone: '',
  ageRange: '',
  eyeShape: '',
  eyeColor: '',
  eyeSize: '',
  noseType: '',
  noseSize: '',
  lipThickness: '',
  mouthWidth: '',
  hairColor: '',
  hairLength: '',
  hairStyle: '',
  facialHair: '',
  scars: '',
  tattoos: '',
  birthmarks: '',
  glasses: '',
  otherFeatures: '',
  height: '',
  build: '',
}

export const FACE_STRUCTURE_FIELDS = ['faceShape', 'skinTone', 'ageRange']

export const FORM_OPTIONS = {
  faceShape: ['Oval', 'Round', 'Square', 'Heart', 'Diamond', 'Oblong'],
  skinTone: [
    'Very light',
    'Light',
    'Medium',
    'Olive',
    'Brown',
    'Dark brown',
    'Dark',
  ],
  ageRange: ['Teenager', '20s', '30s', '40s', '50s', '60s+'],
  eyeShape: ['Almond', 'Round', 'Hooded', 'Monolid', 'Upturned', 'Downturned'],
  eyeColor: ['Brown', 'Black', 'Blue', 'Green', 'Hazel', 'Grey'],
  eyeSize: ['Small', 'Medium', 'Large'],
  noseType: ['Narrow', 'Broad', 'Hooked', 'Upturned', 'Flat', 'Bulbous'],
  noseSize: ['Small', 'Medium', 'Large'],
  lipThickness: ['Thin', 'Medium', 'Full'],
  mouthWidth: ['Narrow', 'Medium', 'Wide'],
  hairColor: [
    'Black',
    'Dark brown',
    'Brown',
    'Light brown',
    'Blonde',
    'Red',
    'Grey',
    'White',
    'Bald',
  ],
  hairLength: ['Bald', 'Very short', 'Short', 'Medium', 'Long'],
  hairStyle: ['Straight', 'Wavy', 'Curly', 'Afro', 'Pulled back', 'Dreadlocks'],
  facialHair: [
    'None',
    'Light stubble',
    'Heavy stubble',
    'Thin mustache',
    'Thick mustache',
    'Goatee',
    'Short beard',
    'Long beard',
    'Full beard',
  ],
  glasses: ['None', 'Thin frame', 'Thick frame', 'Sunglasses'],
  height: ['Short', 'Average', 'Tall', 'Very tall'],
  build: ['Slim', 'Average', 'Athletic', 'Heavy'],
}

export const FIELD_LABELS = {
  faceShape: 'face shape',
  skinTone: 'skin tone',
  ageRange: 'age range',
  eyeShape: 'eye shape',
  eyeColor: 'eye color',
  eyeSize: 'eye size',
  noseType: 'nose type',
  noseSize: 'nose size',
  lipThickness: 'lip thickness',
  mouthWidth: 'mouth width',
  hairColor: 'hair color',
  hairLength: 'hair length',
  hairStyle: 'hair style',
  facialHair: 'facial hair',
  scars: 'scars',
  tattoos: 'tattoos',
  birthmarks: 'birthmarks or moles',
  glasses: 'glasses',
  otherFeatures: 'other notable features',
  height: 'height',
  build: 'build',
}
