export const INITIAL_WITNESS_FORM = {
  gender: '',
  ethnicity: '',
  faceShape: '',
  skinTone: '',
  ageRange: '',
  foreheadSize: '',
  foreheadShape: '',
  eyeShape: '',
  eyeColor: '',
  eyeSize: '',
  eyebrowThickness: '',
  eyebrowShape: '',
  eyebrowColor: '',
  noseType: '',
  noseSize: '',
  nostrilWidth: '',
  noseBridgeHeight: '',
  lipThickness: '',
  mouthWidth: '',
  lipColor: '',
  philtrumLength: '',
  cheekboneProminence: '',
  jawShape: '',
  jawWidth: '',
  faceSymmetry: '',
  earSize: '',
  earProtrusion: '',
  hairColor: '',
  hairLength: '',
  hairStyle: '',
  facialHair: '',
  scarLocation: '',
  scars: '',
  tattoos: '',
  birthmarkLocation: '',
  birthmarks: '',
  glasses: '',
  otherFeatures: '',
  height: '',
  build: '',
  neckLength: '',
  neckWidth: '',
}

/** Required before generating a composite; all other fields are optional. */
export const REQUIRED_FIELD_KEYS = [
  'gender',
  'faceShape',
  'eyeShape',
  'eyeColor',
  'eyeSize',
  'eyebrowThickness',
  'eyebrowShape',
  'eyebrowColor',
  'noseType',
  'noseSize',
  'nostrilWidth',
  'noseBridgeHeight',
  'lipThickness',
  'mouthWidth',
  'lipColor',
  'philtrumLength',
  'hairColor',
  'hairLength',
  'hairStyle',
  'facialHair',
  'scarLocation',
  'scars',
  'tattoos',
  'birthmarkLocation',
  'birthmarks',
  'glasses',
  'otherFeatures',
]

export const REQUIRED_FIELDS = new Set(REQUIRED_FIELD_KEYS)

export const FORM_OPTIONS = {
  gender: ['Male', 'Female'],
  ethnicity: [
    'South Asian',
    'East Asian',
    'Southeast Asian',
    'Middle Eastern',
    'West African',
    'East African',
    'European',
    'Latin American',
    'Mixed',
  ],
  faceShape: ['Oval', 'Round', 'Square', 'Heart', 'Diamond', 'Oblong'],
  skinTone: [
    'Very light',
    'Light',
    'Medium',
    'Olive',
    'Brown',
    'Dark brown',
    'Dark',
  ],
  ageRange: ['Teenager', '20s', '30s', '40s', '50s', '60s+'],
  foreheadSize: ['Small', 'Medium', 'Large'],
  foreheadShape: ['Flat', 'Rounded', 'Prominent'],
  eyeShape: ['Almond', 'Round', 'Hooded', 'Monolid', 'Upturned', 'Downturned'],
  eyeColor: ['Brown', 'Black', 'Blue', 'Green', 'Hazel', 'Grey'],
  eyeSize: ['Small', 'Medium', 'Large'],
  eyebrowThickness: ['Thin', 'Medium', 'Thick'],
  eyebrowShape: ['Straight', 'Arched', 'Flat', 'Bushy', 'Curved'],
  eyebrowColor: ['Black', 'Dark brown', 'Brown', 'Light brown', 'Blonde', 'Grey'],
  noseType: ['Narrow', 'Broad', 'Hooked', 'Upturned', 'Flat', 'Bulbous'],
  noseSize: ['Small', 'Medium', 'Large'],
  nostrilWidth: ['Narrow', 'Medium', 'Wide'],
  noseBridgeHeight: ['Low', 'Medium', 'High'],
  lipThickness: ['Thin', 'Medium', 'Full'],
  mouthWidth: ['Narrow', 'Medium', 'Wide'],
  lipColor: ['Light pink', 'Medium pink', 'Dark pink', 'Brown', 'Dark brown'],
  philtrumLength: ['Short', 'Medium', 'Long'],
  cheekboneProminence: ['Flat', 'Medium', 'High/Prominent'],
  jawShape: ['Sharp', 'Rounded', 'Square', 'Soft'],
  jawWidth: ['Narrow', 'Medium', 'Wide'],
  faceSymmetry: ['Symmetric', 'Slightly asymmetric'],
  earSize: ['Small', 'Medium', 'Large'],
  earProtrusion: ['Flat against head', 'Slightly protruding', 'Protruding'],
  hairColor: [
    'Black',
    'Dark brown',
    'Brown',
    'Light brown',
    'Blonde',
    'Red',
    'Grey',
    'White',
    'Bald',
  ],
  hairLength: ['Bald', 'Very short', 'Short', 'Medium', 'Long'],
  hairStyle: ['Straight', 'Wavy', 'Curly', 'Afro', 'Pulled back', 'Dreadlocks'],
  facialHair: [
    'None',
    'Light stubble',
    'Heavy stubble',
    'Thin mustache',
    'Thick mustache',
    'Goatee',
    'Short beard',
    'Long beard',
    'Full beard',
  ],
  scarLocation: [
    'None',
    'Left cheek',
    'Right cheek',
    'Forehead',
    'Chin',
    'Upper lip',
    'Lower lip',
    'Under left eye',
    'Under right eye',
    'Left temple',
    'Right temple',
    'Left jaw',
    'Right jaw',
    'Left side of nose',
    'Right side of nose',
    'Neck',
    'Bridge of nose',
  ],
  birthmarkLocation: [
    'None',
    'Above left lip',
    'Above right lip',
    'Left cheek',
    'Right cheek',
    'Under left eye',
    'Under right eye',
    'Forehead',
    'Chin',
    'Nose',
    'Left temple',
    'Right temple',
    'Left jaw',
    'Right jaw',
  ],
  glasses: ['None', 'Thin frame', 'Thick frame', 'Sunglasses'],
  height: ['Short', 'Average', 'Tall', 'Very tall'],
  build: ['Slim', 'Average', 'Athletic', 'Heavy'],
  neckLength: ['Short', 'Medium', 'Long'],
  neckWidth: ['Thin', 'Medium', 'Thick'],
}

export const FIELD_LABELS = {
  gender: 'gender',
  ethnicity: 'ethnicity / regional origin',
  faceShape: 'face shape',
  skinTone: 'skin tone',
  ageRange: 'age range',
  foreheadSize: 'forehead size',
  foreheadShape: 'forehead shape',
  eyeShape: 'eye shape',
  eyeColor: 'eye color',
  eyeSize: 'eye size',
  eyebrowThickness: 'eyebrow thickness',
  eyebrowShape: 'eyebrow shape',
  eyebrowColor: 'eyebrow color',
  noseType: 'nose type',
  noseSize: 'nose size',
  nostrilWidth: 'nostril width',
  noseBridgeHeight: 'nose bridge height',
  lipThickness: 'lip thickness',
  mouthWidth: 'mouth width',
  lipColor: 'lip color',
  philtrumLength: 'philtrum length',
  cheekboneProminence: 'cheekbone prominence',
  jawShape: 'jaw shape',
  jawWidth: 'jaw width',
  faceSymmetry: 'face symmetry',
  earSize: 'ear size',
  earProtrusion: 'ear protrusion',
  hairColor: 'hair color',
  hairLength: 'hair length',
  hairStyle: 'hair style',
  facialHair: 'facial hair',
  scarLocation: 'scar location',
  scars: 'scar description',
  tattoos: 'tattoos',
  birthmarkLocation: 'birthmark / mole location',
  birthmarks: 'birthmark / mole description',
  glasses: 'glasses',
  otherFeatures: 'other notable features',
  height: 'height',
  build: 'build',
  neckLength: 'neck length',
  neckWidth: 'neck width',
}
